# Generated by Django 4.2 on 2023-05-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64, verbose_name='用户名')),
                ('user_password', models.CharField(max_length=64, verbose_name='密码')),
                ('create_time', models.CharField(max_length=19, verbose_name='创建时间')),
                ('update_time', models.CharField(blank=True, default='', max_length=19, null=True, verbose_name='修改时间')),
            ],
        ),
    ]
